services:
  event-receiver-server:
    container_name: event-receiver-server
    build:
      context: ..
      dockerfile: docker/Dockerfile_eventreceiver
    ports:
      - "3000:3000"
    networks:
      actinia-dev:

  actinia-worker-http-launcher:
    container_name: actinia-worker-http-launcher
    build:
      context: ..
      dockerfile: docker/Dockerfile_actinia-worker-http-launcher
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      actinia-dev:

networks:
  actinia-dev:
    name: actinia-docker_actinia-dev
